# Generated by Django 2.2.28 on 2024-01-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='points',
        ),
    ]
